#!/bin/bash
#Menu
echo -e " ____    __    ____ .______          _______. __    __    ______   .______   "
echo -e "   \   \  /  \  /   / |   _  \        /       ||  |  |  |  /  __  \  |   _  \  "
echo -e "    \   \/    \/   /  |  |_)  |      |   (----.|  |__|  | |  |  |  | |  |_)  | "
echo -e "     \            /   |      /        \   \    |   __   | |  |  |  | |   ___/  "
echo -e "      \    /\    /    |  |\  \---------)   |   |  |  |  | |  ----  | |  |      "
echo -e "       \__/  \__/     | _| .._____|_______/    |__|  |__|  \______/  | _|  "
echo -e "================================MENU====================================="
echo -e "* menu       : Senarai Menu"
echo -e "* usernew    : Create akaun SSH"
echo -e "* trial      : Membuat akaun trial"
echo -e "* hapus      : Delete akaun SSH"
echo -e "* login      : Check login user"
echo -e "* member     : Senarai user"
echo -e "* resvis     : restart service dropbear, webmin, squid3, openvpn dan ssh"
echo -e "* reboot     : reboot VPS"
echo -e "* speedtest  : speedtest VPS"
echo -e "* info       : Info sistem"
echo -e "* about      : Informasi Tentang script Auto install WrShop"
echo -e "========================================================================="
echo -e ""
echo "hellooo"
speedtest
